### ISSUE TITLE
NewsのTwitterシェアボタン

### ISSUE THREAD

**Issue by solt9029** [MiyashitaLab/miyashita.com#16]
NewsのTwitterシェアボタンからツイートするときに、URLにエンコードされていない日本語が含まれます！
現状
<img width="376" alt="before" src="https://user-images.githubusercontent.com/21151010/34043319-e7f58598-e1e3-11e7-8a26-f9709717a9d0.PNG">
修正後のイメージ
<img width="400" alt="after" src="https://user-images.githubusercontent.com/21151010/34043324-e973eba8-e1e3-11e7-9af0-a87f056c9071.PNG">

**Comment by 3846masa** [comment]
直す前の話っぽいので Close
https://github.com/MiyashitaLab/miyashita.com/commit/5bb86a3750bcd1735e08eac4351a696669f2954d

**Comment by solt9029** [comment]
なるほど！！
