### ISSUE TITLE
論文データベース検索のハイライトがダサい

### ISSUE THREAD

**Issue by mimorisuzuko** [MiyashitaLab/miyashita.com#5]
現状
![2017-06-07 17 50 49](https://user-images.githubusercontent.com/12094729/26870141-ef6d7112-4ba9-11e7-9471-ab5deca6c63d.png)

こんな感じがいい
![2017-06-07 17 50 56](https://user-images.githubusercontent.com/12094729/26870146-f9617b00-4ba9-11e7-802d-72584f547d69.png)

**Comment by 3846masa** [comment]
すごくわかる．
やります．
