### ISSUE TITLE
トップ画

### ISSUE THREAD

**Issue by mimorisuzuko** [MiyashitaLab/miyashita.com#6]
- スマートフォン（iOS, Safari）の黒い余白が気になる
- PCで見た時に小さい
	- こちらに関してはいい感じの画像をトリミングして`width: 100%`でいいと思ってる

![img_1098](https://user-images.githubusercontent.com/12094729/26870502-211dbe28-4bab-11e7-88db-438ba938a0bf.PNG)

**Comment by 3846masa** [comment]
レスポンシブ考えるとトップ画難しい問題ある．
あと， 4K ユーザいるのでそこら辺も考慮しなきゃいけない．

**Comment by 3846masa** [comment]
https://i.imgur.com/hRB3R5L.gif

**Comment by 3846masa** [comment]
とりあえずスマホで見たときの上下の黒帯はなくなったはず

**Comment by 3846masa** [comment]
トップ画像がダサいという点以外は解決した気がするので，一旦閉じる
