### ISSUE TITLE
集合写真を全員写っている写真にする

### ISSUE THREAD

**Issue by mimorisuzuko** [MiyashitaLab/miyashita.com#8]
Slack より
> miyashita.comの今の集合写真に全員写っていないので，写っているものに変えた方がいいのかなと思いました！

**Comment by 3846masa** [comment]
ここを変えてビルドして push すれば ok
https://github.com/MiyashitaLab/miyashita.com/blob/9b28338e1c60290f6dd697e3cc79de0995cc7b46/_source/style/index.css#L5

**Comment by 3846masa** [comment]
写真決めてくれたらやるけど

**Comment by 3846masa** [comment]
やっといた（キャッシュ消えれば変わる）
https://github.com/MiyashitaLab/miyashita.com/commit/ef4c30dbb95b8a32428b5990f3f71a2279a03e11
