### ISSUE TITLE
カードビュー

### ISSUE THREAD

**Issue by mimorisuzuko** [MiyashitaLab/miyashita.com#9]
> 最新情報のカードビューの境界線が黒くてダサいので，色変更か影などにする

![screen shot 2017-09-22 at 20 55 33](https://user-images.githubusercontent.com/12094729/30743418-74486fa4-9fd8-11e7-8a5b-196b8f4788b0.png)

Ref. https://wantedlyinc.com/ja

**Comment by 3846masa** [comment]
案
![](https://i.imgur.com/H8AI172.gif)

**Comment by 3846masa** [comment]
#10 で進めてる branch ではカードビュー良くなったので，とりあえず閉める
